### ISSUE TITLE
Filtering snapshots prior to export

### ISSUE THREAD

**Issue by mew-nsc** [debrief/pepys-import#1025]
## :speech_balloon: Brief description of feature

The ability to apply one or more filters to database snapshots prior to exporting. 
Filters requested:
- Task/Operation
- Geographic area
- Timestamp range

## :bangbang: Business impact
Reduces issues with file size / disk space limitations when exporting data from a lower classification database and importing into a higher classification database

## :100: Acceptance criteria
- [ ] Can filter exports by task/operation
- [ ] Can filter exports by geographic area
- [ ] Can filter exports using a timestamp range

**Comment by robintw** [comment]
I've looked into this briefly, and it's going to be more complicated than we thought, but also will require some more input from the users.

Currently we don't actually export measurement data when we do a snapshot of the database: we only export either reference data or reference & metadata. See the menu given in Pepys Admin:

![image](https://user-images.githubusercontent.com/296686/134673908-34a33c27-cf67-42b8-bbbe-088fbd8c7356.png)

This feature suggests that the users want to be able to export measurement data (States/Contacts/Comments etc) as well. Is this correct? I'm not 100% sure what the use case for this is. This feature was originally designed for exporting the reference/metadata to a standalone database, so that imports of other data could be done in that database while linking to the correct (canonical) objects for Platforms, Sensors etc. And then, after that, the imports done in this standalone database could be merged back into the master database.

The use case listed here seems to suggest that they want to export actual measurement data (like ship tracks) from a lower classification database and import into a higher classification database. Is that right? What would they then be trying to merge afterwards? More stuff from the lower classification into the higher classification? Presumably not stuff from the higher classification back to the lower classification (which would be what this feature would have originally be designed for - when it was for use with an analyst going to sea)? No merging at all?

I'll wait for some responses to these questions before coming up with a plan for how to do this, but it will definitely be more complex than I thought.

**Comment by IanMayo** [comment]
Yes, this new use case involves exporting measurements, too.  This flow of data is to allow the data to be used in analysis on another network.  Data from that network is not expected to flow back into Pepys, but there is a slight possibility.

My guess is that we have to provide sufficient metadata/reference data to support the measurements being transferred, but no other metadata. So we won't need to pass all 350 platforms over.

So, this business process is different to our "Deployed analyst".  Here we're using it as a way of packaging sets of measurements to be used in another instance of Pepys.  Hmm, or, potentially on other systems - if we also provide the recipient with a schema.

**Comment by robintw** [comment]
I've been thinking about this over the last few days, and had a discussion with @mew-nsc about it at standup today. Here I'm going to try and summarise some of my thoughts and the discussion we had.

There are two approaches to this:
1. Export _all_ reference and metadata entries, and then just do a simple SQL WHERE query on the States/Comments/Contacts and export the matching entries.
2. Do a WHERE query to select the relevant State/Comments/Contacts entries, and then find all the linked metadata/reference entries (Platforms/Sensors/PlatformTypes etc) and export those.

Theoretically, option 2 is better as it exports less data. However, in practice I think option 1 might be better. The advantages/disadvantages are:

**Option 1: Export all metadata**
1. **Advantage:** Far simpler to implement from our perspective
2. **Advantage:** The users already have all the metadata/reference data so if they import other things into this database, they won't be recreating metadata entries in two places, potentially with subtly different data (which then may have to be resolved in a database merge). This is particularly important for reference data, where there is a small canonical list that we don't want to end up with 'almost-duplicates' in - so I think regardless which option we choose, we should export all reference data.
3. **Advantage:** Exporting all of this data doesn't actually take very long or take up much space. Exporting all reference & metadata from the TracStor database takes < 10s and produces a sqlite file of ~8Mb. This is for over 500 Platforms, 500 Sensors, and a load of other data.
4. **Disadvantage:** If they add _loads_ of extra platforms etc, then the export could become larger and take longer.

**Option 2: Export just linked metadata**
1. **Advantage:** Only exports the absolutely necessary data, keeping the exported database as small as possible.
2. **Disadvantage:** Requires implementing code to find all of the linked objects. The opposite of this is available already in the `sqlalchemy_utils` library (and we use it elsewhere in the code) - this does the job of finding all the objects that link to a specific object (eg the Sensors that link to a particular Platform), but we want to do the opposite - finding all the objects that a specific object (like a State) depend on (for example, for a State this would be the Datafile, Platform and Sensor objects, plus a load of reference data). This could be implemented using SQLAlchemy code to find the relevant foreign keys, and I've done a bit of playing with this, but it will be fairly complex code. There is a simpler but more fragile way to do this too, but this may break in some situations.
3. **Disadvantage:** This could be significantly slower than just exporting all the metadata/reference data. We'd have to iterate through all of the measurement objects returned, get all of the relationships to other tables, get all those objects etc - as opposed to just doing a few `SELECT * FROM X` queries and exporting the results.

My view is that we should probably go for Option 1. What do you think @IanMayo @mew-nsc?

I'll start making some notes on a plan for implementing this, starting with the bits that will be the same regardless of which option we choose, and then I can flesh out those notes once we've decided on an option.

**Comment by robintw** [comment]
**Rough plan for implementation of this feature: (still in progress)**

1. Modify `snapshot_cli.py` to add new options to export reference & metadata & measurements, filtered by each of the options (one new menu entry per filter type). This requires adding to the string defined at L26, and then adding to the `self.aliases` definition on L36 to link the number of the menu item to a method to be run when it's chosen. New methods will need to be added to do these various exports - I'd copy the `do_export_reference_data` and modify as needed (see below).
2. Add new functions to the `snapshot_helpers.py` file called `export_all_filtered_by_time`, `export_all_filtered_by_space` etc. These should take arguments of source and destination DataStore instances, plus some representation of the filter (`start_timestamp`, `end_timestamp`, `top_left_loc`, `bottom_right_loc` etc).
3. Modify the methods in `snapshot_cli.py` to ask the user for the filtering information. This could be done fairly simply with a simple `prompt` call and then some validation to check they're in the right format. I'd suggest staying relatively simple for this - rather than going into a full GUI for getting the information. For the location, I think the simplest way to specify the filter would be to use a bounding box in lat/lon - asking the user for 'top left lat', 'top left lon', 'bottom right lat', 'bottom right lon'. Pass these parameters to the functions in `snapshot_helpers.py`.

_All of the above will be the same regardless what approach we choose. The rest of this will depend on the choice - I will give a rough plan for Option 1 (exporting all) below:_

4. Inside `export_all_filtered_by_time`, call `export_reference_tables` and `export_metadata_tables` to export all the reference data and all the metadata (they probably have to be called in that order, so that the relevant entries in the reference tables are there when we add the metadata tables which refer to them).
5. Then run a query on each of the measurement tables, adding a filter to filter by the relevant field. Take the results, and export them to a list of dicts (like `[{'field1': 'entry1_value1', 'field2': 'entry1_value2}, {'field1': 'entry2_value1', 'field2': 'entry2_value2}]`) and insert those values into the destination database. This chunk would look something like this:

```
measurement_table_objects = data_store.meta_classes[TableTypes.REFERENCE]

dict_values = []
for table in measurement_table_objects:
    results = data_store.session.query(table).filter(FILTERING_STUFF_HERE).all()
    for row in results:
        d = {column.name: getattr(row, column.name) for column in row.__table__.columns}
        dict_values.append(d)

    object_ = find_sqlite_table_object(table, source_store)
    with destination_store.session_scope():
        destination_store.session.bulk_insert_mappings(object_, dict_values)
```

**Comment by IanMayo** [comment]
Thanks for that @robintw .  I did see a performance benefit in having the minimum relevant platforms/etc on the _other_ Pepys.  But, we're working on performance fixes for lots of metadata - so that problem shouldn't arise.

Hmm, what do we think about the `admin` metadata, like `changes` and `extractions`.  I _Don't think_ we need to export those.  If the audit trail is required it's probably best to do it on the `Master` Pepys - where all data is present.

**Comment by robintw** [comment]
Ah yes, we definitely don't need to export things like `Logs`, `Changes`, and `Extractions`.
