### ISSUE TITLE
Do we need to store the schema version in the database?

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#158]
I'm creating an online PostGres hosting server, for us to use collaboratively.

I've realised that if the schema matures, our Python code may try to connect to a server with an older schema, and fail for unexpected reasons.

In the early stages, these failures should help us make the software more reliable.  But, in the longer term I think we need to understand the versioning.

Below are some thoughts on the issue that I captured last year.  But I now realise we store the schema in the SQLAlchemy code, rather than as SQL - which may prevent the below from being an option.

----

I'm no database expert - this is just a train of thought.

I think we need to _manage_ changes to the database.  

Well, right now we don't, we can just wipe it & recreate it.  

But, once the client has data in the database, that won't be an option. That is - once it's in _production_.

The client doesn't have a PostGres maintainer, or even a database expert.

I was wondering how we could support/manage the evolution of the database as requirements emerge.

Here's what I thought of.

We adopt the practice of capturing database changes on the end of the database creation script.  We use comment markers to separate versions.  
```
/* version:12 */
```

We'd parse the script file, using a regex that matches the above to split it into chunks.
We then include a "Version" table in the database. This is a tabular list of version numbers, and the date at which they were applied.

To update the database, a Python script connects to the database and then:

1. If the Version table isn't present, treat the version number as zero.
2. If there is a version table present retrieve the most recent version number.

With the version number, the composite script can be _split_ according to a regex that matches the above versioning comment. Then:

1. Parse the SQL script, applying all changes _after_ that version number. When a block of lines (that form a version) are applied, insert that version number into the versions table

So, the above process can either create a new, empty database, or non-destructively transform a database structure to a new version.

Aah, some of the above are covered here:
https://enterprisecraftsmanship.com/2015/08/10/database-versioning-best-practices/

Aah, and here's an Open Source tool that supports the migrating schemas:
http://www.liquibase.org/index.html

The above script would be within our version control system - so source changes and database schema changes are handled together.

----
We could include the above process in our library. After our tool has successfully connected to a db, it checks for the versions table.

If it's missing, the tool asks the user if the user wants the database to be created.

If it has got the version number, and can see that number is less than the current one, it asks the user if the user wants to update the database.

Aah, hmm. Applying the updates needs a lot more permissions than an account that just inserts data.

So, if the tool has established that the database needs updating, and the user wishes to run the update, but gets "access denied" - it should prompt the user to use an account/password with higher permissions.

----

**Comment by robintw** [comment]
The general way to deal with these issues is through the use of 'migrations', which are chunks of code that take the database from one version to another. I'm not an expert DB developer, and haven't written many migrations before (and the ones I have written were mostly in Ruby on Rails many years ago), but I understand the concept. A proper migration tool will basically do a lot of what you described above automatically.

The best migrations tool for SQLAlchemy seems to be [Alembic](https://alembic.sqlalchemy.org/en/latest/index.html). It has the ability to write migrations by hand (see [here](https://alembic.sqlalchemy.org/en/latest/tutorial.html) and then upgrade or downgrade the database by hand. However, it also has the ability to 'autodetect' differences between the database and the schema defined in the app (see [here](https://alembic.sqlalchemy.org/en/latest/autogenerate.html)).

This would seem to be a good way to go forward. The only problem is that these migrations are designed to be written by programmers and applied by experienced database administrators - and the upgrades at the client's site are likely to be done by people who are neither of those! Alembic also requires to connect to the database to see what is there and automatically generate migrations, so that would need to be run 'on site'.

So, a few ideas there - but they will definitely need fleshing out a bit more!

**Comment by BarisSari** [comment]
As you all know, I'm trying functionalities of Alembic in the last days. Unfortunately, I've faced many problems. Therefore, it hasn't successfully integrated to our repository yet. I've tried to find a solution for the following issue we discussed earlier:
-  Capturing database changes. Because the client can't wipe and recreate the database once its in production. So, we should somehow keep track of the client's DB version and the current version of the project.

I'm a bit familiar with the migration strategy because I've used it in many different Django projects. It has the following logic: Each package of the Django project has `migrations` folder. With the built-in commands, it is possible to collect the DB models automatically and create migration files. They are python modules but it's possible to convert them to SQL scripts to check. When migration files are created, another command migrates the updates to the DB and saves the insert/update to the migrations table to keep track of it. The good thing about Django's migration is it is possible to use `migration=False` flag in your models. So, if it is set, you aren't allowed to migrate your DB model changes to the DB. But it's possible to do vice versa.

We more or less need the same strategy. When we run pepys_admin or pepys_import, we can check the migrations and warn the user if its DB has missing migrations. We can also try to run the migration automatically after the user approval for the migration.

Alembic has used by many popular frameworks (https://github.com/miguelgrinberg/Flask-Migrate) 
as well. But here are the problems I've faced so far:
- It can automatically generate migration scripts just as Django, however, this auto-generation leads to two main problems. The first one is, it detects Spatial fields and add them to the migration script but it doesn't import `Geoalchemy2` library. I've manually added the import for now but I think we can include it to each migration script. The second problem is a hard one because it tries to drop Spatial tables from the DB when the automatic migration command is run again. An example is as follows:
```python
op.drop_table("idx_Media_location_parent")
op.drop_table("idx_Contacts_location")
op.drop_table("idx_Geometries_geometry_rowid")
```
I'm afraid, there isn't a decent solution yet for this problem. For example, this one suggests creating indexes manually: https://github.com/geoalchemy/geoalchemy2/issues/137
There is another solution: https://gist.github.com/utek/6163250
However, when I modify and use it, it doesn't create spatial tables when the DB is empty this time because they are excluded from Alembic. I believe that there might be another solution, which is to use SQLAlchemy's `create_all()` method for the first migration and stamp the DB with this migration at the beginning. I'm trying this approach for now. I'll update this message when it works/fails.

Another problem is that the developers might have two different databases, SQLite and Postgres.  It means that we should have two different base migration scripts. Alembic offers this: https://alembic.sqlalchemy.org/en/latest/branches.html#working-with-multiple-bases
However, autogenerate command becomes a problem again. Even though I followed the tutorials and searched for it thoroughly, I couldn't autogenerate changes for different DBs. It is possible to create manual migrations with the following commands:
          `alembic revision -m "migration-1" --head sqlite@head`

It creates a new file in the migration folder for SQLite, and you can manually enter your changes. I don't believe that it is what we want.

By the way, Alembic offers: downgrading migrations, creating SQL scripts from migration files(https://alembic.sqlalchemy.org/en/latest/offline.html#generating-sql-scripts-a-k-a-offline-mode), showing the history of migrations, showing the current head of the DB, etc. So, it has many useful functionalities. However, it won't mean anything unless I adapt it according to our needs first. 

Since one week has passed, I wanted to update all of you with my findings/problems. Any feedback&thoughts are welcome, @robintw and @IanMayo . Honestly, I'm a bit concerned because of the problems above 🙂 

**Note:** As @IanMayo suggested on Slack, it is possible to have pure SQL scripts for migrations. However, I don't think that it will be useful for the client or the developers. Because they should figure out the changes from SQL Scripts and apply it to the DB models in `sqlite_db.py `and `postgres_db.py`. Instead of this, I think we should have migrations scripts (in Python) that are created automatically and can be convertible to SQL scripts if necessary(it's what I'm trying to do by now). On the other hand, I don't think that Alembic-SQLAlchemy offers a migration flag for forbidding database changes from models.

**Comment by robintw** [comment]
I'm afraid my knowledge of migrations is fairly limited - but you might be able to get some help by posting on the [Alembic Google Group](https://groups.google.com/forum/#!forum/sqlalchemy-alembic) (there aren't _loads_ of posts recently, but it does still seem to be active) or even just StackOverflow (where there seem to be a lot of questions tagged with `alembic`).

I would guess (hope...!) that the autogenerating issue with two different databases would be something that has already been solved by other people - so hopefully the mailing list/StackOverflow would be able to solve that one.
