### ISSUE TITLE
Can E-Trac files contain depth?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#182]
Currently the depth for E-Trac files is set at a constant 0.

Can E-Trac files actually contain depth measurements? If so, we should extract them. If not, we shouldn't record zero, we should just leave the elevation field blank.

**Comment by IanMayo** [comment]
Yes, the `Alt` column is altitude in metres:
![image](https://user-images.githubusercontent.com/1108513/76300034-f9553380-62b3-11ea-8972-4052f9e8bf8d.png)


They currently contain zeros - but we should be parsing that field, rather than inserting zero.

It _may_ be zero because it's altitude measurement is disabled.  But, we can't go wrong by including the measurement from the file.
