### ISSUE TITLE
User guidance in writing parsers

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#190]
The parser writer(s) could do with some introductory guidance in developing Pepys parsers.

I guess we should cover the following:
* intro to data flow
* elements of parser:
    * import tests
    * parse file:
        * lines
        * tokens (& delimiter)
        * record token usage (extraction highlighter)
        * pint typed-objects
    * create metadata
    * create measurements
* how to develop parser:
    * create offline development environment
    * obtain/generate sample input file
    * write unit test that verifies parser, send data to `test.db`
* how to deploy parser:
    * put parser & tests into relevant folders
    * run pytest, verify nothing breaks

Maybe a nice-to have would be some recipes for handling different issues, though none spring to mind.  Note: we're not teaching Python, we're teaching how to parse the files the Pepys way.  So, we can assume the have moderate Python skills and a good understanding of the file format they're handing.

I propose we collaboratively author the content [here](https://docs.google.com/document/d/1xOszXrBstat7xHkkOXyzTHndpM6ZUrS5lcyzDViiKjM/edit#heading=h.rdu9x3fgpapc), then move it to `ReadTheDocs` on completion.  So, we should be aware of the target publishing environment, and _probably_ minimise the use of images.

**Comment by robintw** [comment]
A few comments/questions on this.

1. This should be written _after_ the getters and setters are dealt with (#142), as this will change how parser authors write things.

2. Are we expecting them to set up a full development environment? Including a local Postgres server? If they don't, then they won't be able to run pytest to do all the tests, as some will fail without a local Postgres server for testing.postgresql to use. I can see two ways around this, if we don't want them to have to install Postgres:

   a) Tell them to just run tests on their new parser (`pytest tests/test_load_blah.py`)
   b) Mark tests that require Postgres and get them to run `pytest -m not postgres`.

3. Where would you like this document written? In the ReadTheDocs documentation, or on Google Docs?

**Comment by IanMayo** [comment]
1. Yes, good point.
2. Hmm, I was going to suggest the `not postgres` strategy, but realised it's not relevant.  They are writing their parsers in a folder _outside_ the Pepys folder (though it's probably adjacent).  So, in their folder they will have `parsers` and `tests`.  They can run `pytest tests` to run through all of their local parsers.  Their unit tests won't be using postgres.  Or if they do, they will have installed a local PostGres.  (the network isn't _too_ locked down, so that would be quite possible).
3. I propose Google Docs in the authoring process, then ReadTheDocs (so it gets deployed to their local network).

**Comment by robintw** [comment]
Thanks.

We will probably need to make some new instructions (or put optional bits in the old instructions) for how to do a dev install just for writing parsers, so they don't try and get Postgres installed without needing to.

Also, if they're writing their code in a folder _adjacent_ to the pepys-import folder then we will need to do something to enable them to access the pepys_import library from their code. At the moment, pepys_import isn't actually installed when we set it up for development work: it just sits in a folder, and as all of the code using it is within that folder it all works fine. For them to develop code outside of the cloned repo folder, we will  need to do one of two things:

1. Actually install pepys_import, using pip with the 'editable' option (`pip install -e`) so that the package is installed and added to the Python import path, but the code is left in the folder where it came from, and everything just points to that folder.

2. Modify the `sys.path` variable at the top of the files using pepys_import from another folder, so that it can find the pepys_import library (a bit nasty and hacky - and those lines of code would have to be removed before distributing.

I think we should go for the installation approach, but this will mean that we will have to sort out the `setup.py` file which is a bit out of date (I think) so that it can be properly installed. I'll need to do some tests on this on Windows.

**Comment by IanMayo** [comment]
Aah, I guess we would need a separate release, that includes the `_dev.txt` requirements.

That's cumbersome.  Probably better to switch to the release including all the `_dev` requirements.  The release will still be fairly compact (considering it contains a full Python exe).

**Comment by robintw** [comment]
It's worth testing it, but I think the release with all the _dev requirements will be a _lot_ bigger, as it will contain things like sphinx that include loads and loads of dependencies. Definitely worth trying though.

**Comment by IanMayo** [comment]
I'll give it a go.

**Comment by robintw** [comment]
Completed in #264
