### ISSUE TITLE
Run-Python script

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#318]
We have the run-python script, which sets the correct path parameters, then runs python.

But, it doesn't get put into the user %PATH%.  So, it can only be run by navigating to the `bin` folder, and running it from there.

That doesn't seem a likely/useful scenario.  But, set-paths does put the relevant Python install onto the CLI path, so `pepys-import` can be run from anywhere - which does seem more useful.

So, to do some CLI pepys importing, these are the steps:
1. open Command Prompt
2. navigate to the Pepys/bin folder
3. run `set-path.bat`
4. navigate to data folder
5. start importing/experimenting/whatever

Hmm, if we had routine to permanently set the Path, the user could omit steps 2 and 3.  Maybe we could/should do that within `create_shortcuts`.    I guess we would rename it to `install_pepys`.

What do you think, @robintw ?

**Comment by robintw** [comment]
I think we discussed this a bit when I was first developing the install scripts, and decided not to put the pepys python install on the path, because it would then take precedence over any other version of Python they had installed.

So, if we changed the install process to permanently change the path, and the user had some other code they were happily running with another installed version of Python, they would then find problems because running `python` from the command line would use the Pepys-installed version of Python - which might not have the relevant packages installed for the work they are doing etc, and would generally mess things up.

One alternative, would be to change the `run_python.bat` script to be called something like `pepys_python.bat` and then put the `bin` folder on the PATH permanently. Then, from anywhere on their system the user could do something like `pepys_python -m pepys_import.import ...blah`. Because the other scripts in `bin` would be in their path too, they should be able to do `pepys_import blah arguments here` and it would be the equivalent of running `pepys_python -m pepys_import.import` (we'd have to do a bit of playing to make sure the `pepys_import.bat` script played nicely with both Send To and running from the command-line, but it should be possible).

We could even shorten `pepys_python.bat` to something like `ppython.bat` or something, if we wanted to make it easier for them to run it (you can also leave off the `.bat` when calling Windows batch files from the command line).

There is also an issue with how to set the PATH permanently from a batch script, and it seems like there might be some permissions issues in doing so, but I can investigate that if we go down that route.

What do you think @IanMayo?

**Comment by IanMayo** [comment]
Aah, yes - I vaguely remember that conversation, and appreciate how we shouldn't _mangle_ their environment.

If the `bin` folder was on their path, they could type `set_paths` from the CLI in any folder, and then just type `python -m pepys_import.import --db test.db` (for example) from the current folder.

We would have "manged" their environment by forcing use of our Python instance.  But, it would be cleared as soon as the user exited the Command Prompt.

**Comment by robintw** [comment]
Fixed by #324
