### ISSUE TITLE
Error in is_schema_created if a file created on Windows is used on OS X/Linux

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#326]
As we're using a different version of mod_spatialite on Windows (because it's the only version that is compatible with our version of Python), it creates two extra geospatial tables when mod_spatialite is set up. This means there are different numbers of tables created on Windows and on other operating systems.

We have a line of code in `is_schema_created` saying:

```python
number_of_tables = 72 if platform.system() == "Windows" else 70
```

The problem is, if we create a sqlite file on Windows and then try to load it on OS X/Linux, we get an error because the number of tables doesn't match the platform that it's operating on.

This won't be a problem for deployment, as they're all using Windows (and probably won't be sharing SQLite files anyway).

We could just allow either 72 or 70 tables, or we could try and check the one we expect and then print a warning and continue if it is the other one.

Also, I don't know whether this means a file moved from Linux/OS X to Windows will work properly or not - I don't know if it will mind that a couple of tables are missing, or whether it will create them or what. That needs investigating.

**Comment by IanMayo** [comment]
Being able to use still use database files created on MS-Windows on Linux/MACOS seems good - so yes, let's relax the test on Linux/MACOS.

Yes - this does still need further investigation, particularly on what happens if we load a Linux/MACOS database on MS-Windows.  Trying to export a `States` datafile from `pepys_admin` should prove if it works or not, since that access the `blob` in the `location` column.
