### ISSUE TITLE
Need to move away from hard-coded metadata for platforms

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#350]
Our data importer modules have a shared history, mostly coming from the first REPLAY file importer we created.

It's no surprise that they all include hard-coded values for the platform:
![image](https://user-images.githubusercontent.com/1108513/81070168-c9549600-8eda-11ea-899f-58a56c3e04a2.png)

We should remove these values, and leave it to either the CLI or the defaults-resolver to fill in the gaps.

Sadly this means more work for the user, but it is the real data that they need to enter.

**Comment by robintw** [comment]
I've done a preliminary removal of some of the hardcoded metadata, but have a few questions:

1. Is it still ok to specify a sensor name of `GPS` in the GPX importer? Presumably all GPX data will be GPS - but will they need to potentially have more detailed sensor names, so we should leave it as `None` for the command-line resolver to get the user to enter it?

2. In the REP importer, we set the sensor_name to the platform name - so when importing data for the submarine SPLENDID, it wants to create a sensor called SPLENDID. Is this right? I've noticed it isn't actually possible to edit the name of the sensor once it asks you - it says: 

```
Sensor 'SPLENDID' not found. Do you wish to: 
   1) Search for existing sensor
   2) Add a new sensor, titled 'SPLENDID'
   .) Cancel import    
```
Do we need to add an option to add a new sensor with a different name? The same pattern appears in a number of other importers: we add a new sensor named after the platform.

3. Do we want a hard-coded sensor type or sensor name for any of the other importers? For example, the ETrac importer has a hardcoded sensor_name of `E-Trac` and a hardcoded sensor type of `GPS`. Similarly, the REP Comment importer has a hardcoded sensor type of `Human`, which makes a certain amount of sense to keep?

**Comment by IanMayo** [comment]
1.  Yes, for now let's GPX as a 'special case'.  If the clients want us to make it more specific we can.  I don't think it's encountered very often.
2. Sadly we can't use platform-name as sensor-name in REP data.  We do need to ask the user what the sensor is (if we're in CLI importer, obvs).  Yes, let's change the wording of Option 2: `Add a new sensor, default name 'SPLENDID'`
3. Actually, both of those examples seem valid.  E-Trac is GPS, but it's a special "bolt-on" fitted just for exercises.  So, calling it `E-Trac` is fine.  But, I'll have to give feedback on other instances as you encounter them.

**Comment by robintw** [comment]
Thanks.

I've kept the hard-coded sensor names for GPX, E-Trac and REP Comment importers.

However, when removing the hard-coded sensor name for the REP importer, we now get asked to choose a sensor (with the `Search for existing sensor` or `Add new sensor` prompt) for every single line of the REP file...!

I assume this is because the REP file doesn't actually contain information on the sensors (I think it does for the contacts, but not for the main REP location data). It does, however, have information on the platform in each row. Do we want to keep track of a dictionary of platform to sensor object mappings in the REP importer, so that once we've defined a sensor for a platform, we use that sensor for every other row that has that platform?

The other issue with this is that when we tell the user that the sensor isn't found, we don't give them any other information so that they actually know what sensor we're talking about! Do we need to provide the platform name in the prompt? For example, if you agree with the paragraph above then we could have multiple platforms in each file - and each of those will need a sensor defining for them. At the moment, the user won't know if they're defining a sensor for the 1st platform in the file or the 2nd platform in the file - so I think we need to tell them.

Another issue (yes, we seem to be uncovering quite a few issues now!) is about names of sensors. Sensors stored in the database are associated with a host (a platform). However, when we search sensors in the command-line resolver, we just search by name - without filtering by platform (in fact, that function doesn't actually have platform passed to it - we'd need to do a bit of re-designing to get platform passed to that function). Presumably there could be lots of different sensors, each attached to different platforms, but with the same name? Eg. there could be lots of GPS sensors, and we need to make sure we only offer the GPS sensor that's attached to that specific platform as an option? Am I right? If so, we'll need to re-design things a bit so that we pass platform around a lot more, and use it for filtering. The same may apply to some other resolver situations - I'd have to look to see.

**Comment by IanMayo** [comment]
All valid. Will try to respond later this evening.

**Comment by IanMayo** [comment]
1. Dictionary of platform to sensor. Yes, good solution.  It will break if a file contains more than one sensor for a platform, but let's wait and see.

2. Yes, we'll need to indicate which platform the user is creating a sensor for.

3. Yes, the sensor search will have to be sensors for that platform.

**Comment by robintw** [comment]
These changes are opening many cans of worms of things that we thought were working ok, but actually fail in interesting ways when some of the details aren't hardcoded anymore. I'm working through the issues gradually in #351, but it's taking a while.

As a break from fixing things that broke, I've been through each of the importers and checked what is still hard-coded. The list below shows everything that is hardcoded in the importers - can you @IanMayo check that these are correct:

**E-Trac importer:**
    Sensor Type hardcoded to GPS
    Sensor Name hardcoded to E-Trac
    
**GPX importer:**
    Sensor Type hardcoded to GPS
    Sensor Name hardcoded to GPS
    
**NMEA importer:**
    Sensor Type hardcoded to GPS
    Sensor Name hardcoded to Platform Name **(Is this wrong?)**
    
**REP Comment importer:**
    Sensor Type hardcoded to Human
    Sensor Name hardcoded to Platform Name **(Is this wrong?)**
    
**REP Contact importer:**
    Nothing hardcoded (Sensor Type resolved by resolver, Sensor Name comes from file)
    
**REP importer:**
    Nothing hardcoded (Sensor Type and Sensor Name both resolved by resolver)

**Comment by IanMayo** [comment]
Answers here: https://docs.google.com/spreadsheets/d/16kzat470Npo0WGQvCPpeP3Du2S-d0LuU4QZbiio6DNk/edit?usp=sharing
