### ISSUE TITLE
Ensure timezones work correctly

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#424]
It turns out that SQLite and Postgres deal with timezones differently. Basically, Postgres deals with timezones when you insert stuff, and then returns times with the timezone specified in the config file. SQLite just ignores timezones (when data is imported through SQLAlchemy at least).

So, a few things come from this:

1. We need to ensure we're storing UTC in the database all the time. At the moment some importers (definitely the GPX importer, but possibly others) import times with a time zone - so we need to change that to convert it to UTC before importing it - so it works properly for both SQLite and Postgres. We also need to add some tests to check we're importing the correct times.

2. We need to check that the Postgres database is set to return times in UTC. This can be done with a SQL command at the beginning of the session, or set in the configuration file. I don't know what the default will be for the client's install - on my OS X machine it defaults to `Europe/London` (presumably it copies the OS X timezone info).

3. All of the times for created and modified dates are ok, as they are all being set with Python's `datetime.utcnow` function.

So, a couple of questions for @IanMayo:

1. It seems like the GPX format can include time-zone information in the timestamps (see `gpx_1_0.gpx` for an example). These were being passed, and therefore timezone-aware objects were being passed to the database causing problems. Can you confirm whether any of the other formats can include times in anything other than UTC?

2. Where do you think it is best to set the timezone for the Postgres database? I guess it partly depends on how easy it is to change the client's Postgres config - so maybe it's easier to set it in SQL at the beginning of each session (when we load the PostGIS extension)?

**Comment by IanMayo** [comment]
1.  Yes, we need to ensure we're storing UTC.  Since ships/aircraft travel through timezones, and/or may have to synchronise actions with organisations in another timezone, time on board is normally set to UTC.  So, almost all systems return the time in UTC.  If a system stores data in a non-UTC timezone we should convert it on import.  I can't think of any other imports that can include timezone.  None of the ones we currently support.

2.  It's important that we tidily handle it in SQLite, since they will be created ad-hoc, and may well be on a system set to another timezone (such as BST).   For PostGres they're an "enterprise" level backend, typically with support available.  So, it wouldn't be unreasonable for us to direct them to update the timezone.   But, if we can do it easily, then yes - it's fine to do it at the start of each session.

**Comment by robintw** [comment]
This was easier to fix than I thought: we're already using timestamps without timezones (ie just in UTC) in the databases - so it was just an error in importing the GPX data.

I've fixed this in #425 along with adding tests specifically to catch timezone errors.
