### ISSUE TITLE
Reduce risk of accidental deletion

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#430]
When writing the instructions for importing CSV reference data earlier, and including a step to delete the database schema, it struck me that it would be very easy for a user to accidentally delete the entire database schema or the entire database contents by selecting the wrong option in Pepys Admin.

A few notes/comments on this:

1. I remember something about different users connecting with different config files which have different permissions. Does this mean that most users don't have the ability to delete the schema? Would they, however, have permissions to delete the entire contents (which is one of the other options in Pepys Admin).

2. Is it worth adding a 'Are you sure?' prompt to Pepys Admin for the destructive operations? These would be:
 - `Clear database contents`
 - `Clear database schema`
 - `Migrate` (as it could potentially cause data loss - and definitely changes the schema)

3. Do the client have backup plans for their Postgres instance? Are they automated and tested properly. I'd hate for them to lose everything because of either a mistake by one of their staff, or (worse) a programming error by one of us.

Thoughts @IanMayo?

**Comment by IanMayo** [comment]
1. Yes, the intention is to have different levels of user.  That won't relate to us, but I expect we'll have to do some permissions-related error handling in Pepys-Admin.  Once the clients are near the point of adding the new, lower-permission accounts, and develop a plan, we can trial that plan in our ecosystem.

2. Yes, that's a good idea.  The warning on `Migrate` should probably be less threatening, since it's part of the normal upgrade process.

3.  Yes, the Virtual Machine is backed up.  But, there are more specific Postgres backup strategies that should also be considered.  We also keep a copy of all those input datafiles, though it would require a lot of analyst effort to re-load them.
