### ISSUE TITLE
Incorrect highlighting in EAG importer

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#484]
The highlighting appears mistaken in the EAG importer:
![image](https://user-images.githubusercontent.com/1108513/85007833-fdff7280-b153-11ea-9835-39ef11021e70.png)

I think columns 5 & 7 should be blue (for location) and column 6 should be red (for altitude).

**Comment by robintw** [comment]
Unfortunately this is a bit complex: we actually use all three columns for calculating location, and all three columns for calculating altitude. Because of the various bits of trigonometry involved, the formulae use all of the X, Y and Z values for each calculation.

At the moment, we record two extractions (one for location, one for altitude) for the same combined token consisting of all three entries. The code for creating the highlighted HTML file then combines the two colours (blue and red) and gets that grey colour.

What do you think is the best way forward? Should we just call `record` once, saying that we've extracted location _and_ altitude from those three columns?

**Comment by IanMayo** [comment]
> we actually use all three columns

Oh, that's a surprise

> combines the two colours (blue and red) and gets that grey colour.

Aah, so that's why it's happening.

> Should we just call record once, saying that we've extracted location and altitude from those three columns?

Yes, good plan.
