### ISSUE TITLE
Document regex use for splitting a Line into tokens

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#492]
The `tokens` method of a `Line` object is confusing. The documentation and variable names suggest that the argument should be a regexp for the character to split on: therefore to split on a `/` it would just be `/` - however, it seems that the regexp given is the opposite: that is, a regexp for the string to find between the separators.

There may be a good reason for this - for example, problems with splitting CSVs otherwise, due to all the issues that CSVs have in general - but it appears confusing at the moment.

We should either switch this to giving a regexp for the delimiter, or document the current approach thoroughly.

@BarisSari Would you mind giving feedback on what you think it is currently doing and why? I think you had engagement with this code more recently than me, so you may understand it and the motivations behind it better than me.

**Comment by BarisSari** [comment]
You're right @robintw . It's confusing because `CSV_DELIM` and `WHITESPACE_DELIM` variables match and group a bit differently but they're both for finding the contents between separators. When `WHITESPACE_DELIM` is used, it only takes non-whitespace characters:
<img width="935" alt="Screen Shot 2020-06-20 at 11 33 28" src="https://user-images.githubusercontent.com/41292272/85197483-e0641180-b2e9-11ea-9183-33181c2b2d73.png">
So, the loop iterates over each found character group (`;;`,`ASSET`,`Build`, etc. for the first line)

When CSV_DELIM is used, it takes characters between `,`:

<img width="935" alt="Screen Shot 2020-06-20 at 11 47 20" src="https://user-images.githubusercontent.com/41292272/85197755-ce836e00-b2eb-11ea-9d78-7bbac2ab9de1.png">


`CSV_DELIM` matches `,` as well but it doesn't group it. So, it groups only the found characters. (`privacy`, `file_type`, etc. for the first line)

I think the reason is preventing duplicated values with small typos. For example, if there is an extra whitespace (let's say `NELSON` and `NELSON `) and you try to split it using only " ", it will create two entries. We might use `strip()` but I don't think it is appropriate all the time. For CSV files, I think it's more problematic because some columns might have quote marks, so this approach takes the content inside of the quote mark (`DATAFILE 2`) instead of this kind of entries `"DATAFILE 2"`.

My suggestion is documenting the current approach thoroughly. If we switch to use regexp for the delimiter, we should do some extra preprocessing to remove whitespaces, quote marks, etc. . Does it sound sensible to you, @robintw ?

**Comment by robintw** [comment]
Yes, I agree we should document the current approach more carefully. I'll do it soon.
