### ISSUE TITLE
Fix Validator when speeds are measured or calculated to be zero

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#556]
Quote from Slack below:

Next error:
```
"REP Importer - Enhanced Validator Error on Timestamp:2020-07-10 00:03:06.015000, Sensor:1084, Platform:  Northumberland":
"Calculated speed (0.047 meter / second)is more than the measured speed  * 10 (0.000 meter /second)!"
```

This looks like a special case.  As the speeds get very slow, rounding errors (well, maybe quantisation) may result in a zero speed. Hmm, I guess that if the measured speed is zero we mark any speed up to 1 m/sec as valid.

**Comment by IanMayo** [comment]
Users have been frustrated again today.  They have a data source that doesn't contain course and speed.  So, these columns are zero.

We should skip enhanced validation if BOTH course and speed are exactly zero.

**Comment by BarisSari** [comment]
Hello @IanMayo . I have a question. You say that the data source doesn't contain course and speed. Doesn't it mean that these values are `None` instead of `0.0`? I added an if clause to skip the enhanced validator when they both are zero. But I want to be sure that this will be enough to solve the users' issue.

**Comment by IanMayo** [comment]
Yes, the values are `0.0` (or just `0`).  They're not the value `None`.

**Comment by IanMayo** [comment]
Change in plan.  We're going to allow the analyst to skip enhanced validation, in #562
