### ISSUE TITLE
Make it easier to use the 'Run SQL query' function

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#639]
## 💬 Brief description of feature

At the moment, raw SQL queries have to be written with lots of quoting - for example `select * from "pepys"."Datafiles"`, and you have to get the case right too (`datafiles` vs `Datafiles`). It would be good to make this feature easier to use by removing the need for quoting, possibly normalising case, and so on. Adding autocomplete for tables/columns would make it even easier, but might be too much work.

## ☑️ Business impact
When an administrator needs to run raw SQL queries they're probably in a stressful situation anyway (often it will be because something has gone wrong). We should make it as easy as possible for them to run these queries.

### Efficiency of analysis
They would save a lot of time, rather than writing lots of invalid queries and having to experiment to fix it.

## ☑️ Acceptance criteria

- [ ] Queries no longer require lots of quoting
- [ ] Queries are converted to the correct case if the case is wrong
- [ ] (Possible extension task) SQL autocomplete is enabled

**Comment by arunlal-v** [comment]
I don't have much idea on the "'Run SQL query'" in pepys-import. But the case restrictions were brought in because the tables were explicitly defined in the DDL scripts in that specific case (sentence case.)
By default, object names in Postgres don't have any case (as can be seen in this SQLFiddle: http://sqlfiddle.com/#!17/8cf7f/1 and http://sqlfiddle.com/#!7/8cf7f/1/0 )
So, this feature can be achieved by redefinig the tables without the double quotes in the DDL scripts/SQLAlchemy scripts. But the flip side is that tools designed to work with the previous versions of these tables (i.e. "Datafiles" instead of datafiles) will return with a "Relation does not exist" error.

**Comment by IanMayo** [comment]
Close this. I've found the in-app guidance sufficient to know how to format queries.
