### ISSUE TITLE
Research supporting import highlighting in XML

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#647]
Our import highlighting is really value for authors producing a new importer, or for an analyst who wants to double-check all the content got imported.

But, it doesn't work for XML, since we use an XML processing library.

This is a research task to consider how we could provide highlighting for the import.

I guess the options are:
1. extend our extraction code to support XML (though we'll need lots of code to handle the full range of XML :-( )
2. extend XML library to collect character index data necessary for producing highlighter 
3. use some new piece of code to "bind" the XML processing with our import highlighting

**Comment by IanMayo** [comment]
@robintw & @BarisSari - either of you would be quite capable with this, though I think @BarisSari has more familiarity with the import highlighting.

But, I think the best outcome for this would be from one of you doing the research, and discussing findings with the other.  I don't mind who does what role 😸

**Comment by robintw** [comment]
Actually it was me who worked on the import highlighting. I'll look into how best to do this and then discuss it with Baris.

**Comment by robintw** [comment]
I've done some investigation into how to deal with highlighting for XML files, and have come up with a proof of concept that shows my plan works. There is a fairly rough notebook showing the proof of concept available [here](https://github.com/debrief/pepys-import/blob/highlighting-xml/XML%20Highlighting%20Playground.ipynb) but note that the highlighting output isn't actually showing properly on Github's view of the notebook. The actual output example highlighting for a tiny XML file looks like this:

![image](https://user-images.githubusercontent.com/296686/101615671-4cf0db00-3a06-11eb-9f11-8656706a8f16.png)

Now, I'll go into the various options I considered, and why I went down this route for the proof-of-concept.

My starting point was to decide that we definitely _do not_ want to implement our own XML parser using the `Token` objects that we already have provided through the highlighting functionality. XML is actually a fairly complicated format, and creating a parser that will work on a full range of real-world HTML files would be a _lot_ of work, and would likely end up being very fragile. Thus, we need to find a way to get character index information from an existing XML parsing library. Once we have this character index information (eg. that the content of the `<course>` tag starts at character 179 and finishes at character 183) we can easily fill in details in the character array stored as part of the `HighlightedFile` class, and get our highlighting working.

Given that, we need to find a way of getting character location data for specific bits of a XML file out from an XML parser. We currently use the [lxml](https://lxml.de/) library for XML parsing. This does not provide character index information from the parser. However, the lxml interface that we're using (`lxml.etree`) is just a slightly fancier implementation of the [ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html) module from the Python standard library. Unfortunately, this doesn't provide character index information either. It seems that there aren't any tree-based Python XML parsers that provide character information - so we have to be a bit cleverer.

One of the Python XML parsers included in the standard library is built upon the [expat](https://libexpat.github.io/) XML parsing library. This _does_ give character index information, based on which character the parser is at when it finds a new part of the XML file (a new element, some new text, etc). Luckily, the Python ElementTree module is based on the expat parser, and has also been designed to be very customisable. Specifically, the `parse` function in the `ElementTree` module can take a custom `XMLParser` instance, and that parser instance can take a custom `TreeBuilder` instance which it uses to actually create the tree of `Element` objects representing the XML file. The `TreeBuilder` class has various methods which are called on events from the underlying parser - for example, the `start` method is called when the underlying parser finds the start of an XML tag; there are also `end` and `data` (for raw text in the file) methods - as well as some others which aren't so important.

Therefore, we can create a custom `TreeBuilder` class which keeps a reference to the parser object, and uses that to extract the current byte index of the parser when one of these methods is called. We also create a subclass of the `Element` class from the Python standard library, and give it some extra attributes to store the start and end characters of the overall element, and the start character of the text within the element (if you have something like `<message>TEXT HERE</message>`).

Because we're using a subclass of the standard `Element` class, all of the rest of the ElementTree API works completely normally. This means you can still use XPath-style expressions to search through the tree of elements, or access the tree manually through methods like `getChildren()`.

Going further: we can also pass a `HighlightedFile` instance to the `TreeBuilder` class, and make sure that gets passed to all the `MyElement` objects, so that we can then implement a `record` method on an element. This means the final API would be as simple as this:

```
doc = parse(path_to_file)

el = doc.find(".//ele")
el.record("XML parser", "Elevation", float(el.text))

el = doc.find(".//time")
el.record("XML parser", "Time", "Parsed time")

el = doc.find(".//speed")
el.record("XML parser", "Speed", float(el.text))

el = doc.find(".//course")
el.record("XML parser", "Course", float(el.text))
```

(Obviously real parser code would have more error checking and so on, and would iterate over outer elements and so on).

This API makes it very simple for parser-writers to deal with highlighting from XML files without having to worry about the details of the XML parsing.

I should point out that the proof-of-concept is rather messy at the moment, and will be cleaned up and improved a lot in the final version - this version was just to prove that it worked.

### Advantages
- We keep the same ElementTree API and can use all of its functions, like XPath searching
- We can provide a 'record` method on an `Element` object so that the highlighting calls are kept right next to the code that is doing the actual XML parsing
- It is quite a 'clean' way of doing this (I was quite proud of coming up with it actually)

### Disadvantages
- It is slower than using the built-in Python ElementTree module. The Python module defaults to using the C implementation of ElementTree, but as we need to fiddle with some of the internals we can't use the C implementation. Preliminary speed tests show that it is about 4 times slower than using lxml - but still only takes around 100ms to parse a 25,000 line example GPX file (note: this is the XML parsing itself, and doesn't include searching in the XML tree later, or all of the Pepys stuff for creating States etc). @IanMayo: It would be useful to know roughly what sort of size GPX files the users are parsing, so we can check it doesn't take too long for their sort of files. I imagine our overhead from the XML parsing will be a lot less than the overhead from creating all the State objects etc, but it would be good to test this
- It is harder to extract locations of attributes. For example, in GPX files we have something like `<trkpt lat="22.1862861" lon="-21.6978806">`. It would be good to extract these two attributes separately so that we can highlight them separately. Unfortunately the underlying XML parser doesn't provide events for finding the start of an attribute, so the only location the parser gives us is the start and end of the whole element. There are a few possible ways forward here:
  - Don't bother extracting the individual attributes, and just highlight the whole opening element showing what has been extracted (possibly with multiple highlights which will automatically overlap and average the colours)
  - Write a bit of code to parse attributes from within a XML tag. We'd need to make sure that we did this robustly (dealing with character escaping etc), but then we could store locations for each attribute within the Element object and enable a slightly more complex `record` API (see below)
- It can get a bit more complicated if we have multiple separate bits of text within an element. For example, something like `<message>Text<details>blah</details>with more text here</message>` - we might need to extend this to keep an array of text start and finish locations and combine them (like we do with `combine_tokens` in the non-XML parsers).
- The ElementTree module's XPath searching doesn't support the full XPath syntax (unlike lxml, which I think supports it all) and this makes a few things more difficult. Specifically, GPX files can have namespaces in them which are then used in the tags. This makes it harder to search for tags (you have to know the namespace, which may or may not be present and may be mangled). Luckily in recent versions the ElementTree module has extended to support the same 'namespace wildcard search' as lxml, but this is only available in Python 3.8 or above. The easiest way around this would be to upgrade to running Pepys on Python 3.8 (we control the Python version used in the deployment, so it would be a fairly easy change), but if we can't do that then we may be able to provide a local copy of the ElementTree module from Python 3.8.

A potential final `record` API that would allow highlighting of different bits of the XML tag depending on what we were actually extracting could be something like this:

```
# Record the text content of the tag
element.record(type='content', ...) # Other arguments to give the name of the thing we're extracting, the value and so on
# Record the full tag
element.record(type='tag', ...)
# Record a specific attribute
element.record(type='attribute', attrib_name='latitude', ...)
```

### Other options
The only other option I can really think of (apart from writing our own full parser), would be to use something like the `expat` parser under the hood, but build up our own tree data structure from the element objects. I did investigate this, but it would mean we couldn't use ElementTree's searching methods using XPath-like expressions and so on - making it a lot harder to use.

I'm aware that was a _very_ long post, but I wanted to explain my reasons behind all of this. What do you think @IanMayo @BarisSari?

**Comment by IanMayo** [comment]
Yes, fully behind this @robintw . 

1. **Performance** - I'm not scared by the 4x increase in speed.  _If_ it becomes an option then the importer could be modified to not perform highlight reporting, or we introduce a max line cut-off beyond which highlighting isn't required.  To be honest, the greatest value of highlighting is probably during development, and while the importer is being adopted.  Beyond that - our progress indicators do a good job of managing the user expectations.
2. **Strategy** - Yes, I'm quite happy with your adopted strategy. Actually the libs you referred to seem quite familiar, I think I briefly explored a similar route when initially implementing the highlighting
3. **Attribute highlighting**  - I think it's ok to stick with element level highlighting.  _If_ we encounter a format when it's a single element per time step, with all data represented as elements, then I think that will justify attribute-level highlighting.
4. **Overlapping elements** - while that is common in HTML/XHTML I don't think it gets used much in our domain.
5. **Python 3.8 upgrade** - sure, I'm fine with that, if you think `3.8` is stable enough. (it is over 12 mths old, I think)

**Comment by BarisSari** [comment]
Thanks for the detailed post, @robintw. I'm actually not much familiar with XML parsers. But, I always support to use built-in classes & modules as much as we can. So, I'm glad that you found a way to tweak `ElementTree` and `TreeBuilder`. For me, the advantages of this approach outweigh the disadvantages.

**Comment by IanMayo** [comment]
> But, I always support to use built-in classes & modules as much as we can

My thoughts exactly :-D

**Comment by robintw** [comment]
I'm starting to implement this now, and have a question @IanMayo:

The positioning information we're able to get from the underlying XML parser come in terms of _byte_ offsets, not _character_ offsets. This means that if there is anything except ASCII characters in the file then it becomes difficult to link byte offsets to character offsets - as some characters can be multiple bytes. I can't see an easy way of linking byte offsets to character offsets in Python, so my question is: can we ignore this and just convert all XML files to pure ASCII before loading them?

There are conversion functions provided in the Python standard library which will convert from any sort of encoding to ASCII, either ignoring non-ASCII characters, or replacing non-ASCII characters with a `?`. Does that sound ok to apply to a file before XML processing?

My immediate thought is that this will be ok, as the only place we are likely to get unicode characters is in the names of foreign vessels - and even then, I imagine a lot of the time these will be recorded in pure ASCII (eg. `e` not `é`). I seem to remember elsewhere in the code we're assuming ASCII too. If a platform name appeared in some files with an accent and some files without, then the user could easily assign a synonym.

What do you think?

**Comment by IanMayo** [comment]
Yes, converting to XML sounds fine.
