### ISSUE TITLE
Sensors are per-platform

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#71]
In the sensors table, we will be storing the sensors for specific platforms.

So, there won't just be a single "GPS" sensor.  There will be a GPS sensor for each platform that is carrying a GPS sensor (or even multiple instances per platform).

That is the role of the `host` field in the Sensors table.

This is a current code snippet for getting a sensor.
```
                sensor = platform.get_sensor(
                    session=data_store.session,
                    all_sensors=all_sensors,
                    sensor_name="E-Trac",
                    sensor_type="GPS",
                    privacy="TEST",
                )
```
Note that `all_sensors` includes all sensors in the database.  Instead of this, within `platform.get_sensor` - the all_sensors should be the list of sensors for this platform.

**Comment by BarisSari** [comment]
In missing data resolver PR, I removed `all_sensors` argument from **_get_sensor()_** because we have **_find_sensor()_** now, which checks whether a `Sensor` entity exists or not. As far as I understand, I should filter not only by **sensor name** but also with the **platform (host)** because **sensors** will be specific for **Platforms**. It's an easy change because I'll add one more filtering. However, I would like to ask a question about your note:

> even multiple instances per platform

Does that mean that sensor names will be duplicated and the filtering by sensor name and platform is not enough?

**Comment by IanMayo** [comment]
> even multiple instances per platform
Yes, but it's not all that bad.
"GPS" will probably be a `sensor-type`. So, a platform could have sensor:"Sony" of type:"GPS", and sensor:"Panasonic" of type"GPS".  
For redundancy reasons, they may even have two of "Sony" on board.  In that case, the platform will have already named them "Sony:A" and "Sony:B".  So, we can rely on Sensor Names as being unique for a platforms (avoiding the duplication will happen outside Pepys).

**Comment by BarisSari** [comment]
Okay then, I'll change find_sensor method and include this issue to the resolver PR.
