### ISSUE TITLE
Respect custom sort order in drop-down tables in Pepys-Maintenance

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#749]
## 🐞 Overview

I'm playing with the new Pepys-Maintenance UI.

I'm selecting the Nationality to match to platforms.  The nationalities are (quite naturally) presented in alphabetical order.

But, for Nationalities we do have a `Priority` attribute. The drop-down would be easier to use if we respected this priority.

I _think_ we only have priority for `Nationalities`, though there may be other instances in the future as reference tables grow.

**Comment by robintw** [comment]
Fixed in 5ccdcf5c.

I also made the privacy name dropdown sort by the privacy 'level' - I think it was sorting by that coincidentally (because alphabetical order seems to be pretty much the same as sorting by level, for the privacies we happen to have defined) - but now it is properly sorting by level.

![image](https://user-images.githubusercontent.com/296686/106622282-56f90b00-656b-11eb-9f8d-a830b6dfae1b.png)
