### ISSUE TITLE
4.3 Split Platforms

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#766]
## 🐞 Overview
Backend processing to split one platform into several instances.

The underlying issue here relates to the "Merlin" helicopter:
![image](https://user-images.githubusercontent.com/1108513/108058007-4d7fa080-704b-11eb-8b29-7c3e5eae6d45.png)

When data from this type of helicopter has been imported, it has mistakenly been imported into a single "Merlin" platform. The correct use of Pepys would have been to have one "Merlin" platform per aircraft, each uniquely identified by the airframe number (ZH860 in the following image).
![image](https://user-images.githubusercontent.com/1108513/108059155-fed30600-704c-11eb-89ee-158443f83480.png)

So, this task is to allow analysts to split a single Platform into multiple ones.  It is assumed that one Merlin datafile will only contain data for a single Merlin.

## API

* Receives: PlatformID
* Processing:
    - find list of datafiles for this platform
    - duplicate platform, once per datafile, using date-time of first measurement for datafile as "identifier" yymmdd-hhmmss
    - re-assign datafile to the new platform
    - duplicate sensor(s) in new platform as necessary to ensure sensor is present for measurements in that datafile. 
* delete original platform
* log changes (splitting original platform, creating new platform)

## 🔗 Feature

#600 Maintenance tools

## 🔢 Acceptance criteria

* Database initialised to contain several datafiles for same platform
* call split function, passing platform id
* verify there's now one platform per datafile, and that each platform has the correct sensor

**Comment by BarisSari** [comment]
Hello, @IanMayo. I have made progress on this issue, but I have a few questions. As you know, there is no direct relationship between Platforms and Datafiles tables. I have found 3 types of relationships. First, I find all related objects of the given Platform. Then: 

1. If it's a `Sensor` object, get one child object of that `Sensor`. Then, find the child object's datafile_id and the first date of the measurements.
2. If it's either one of `Media, LogsHoldings, Geometries, Comments, Contacts` objects, find datafile_id and the first date of the measurements.
3. If it's a `HostedBy` or `Participants` objects, don't do anything. I couldn't find a relationship to find out which datafile is related to these tables. So, for now, they are deleted when the split platform is deleted. Can you help me to solve this problem? What should we do to handle these tables?

<img width="951" alt="Screen Shot 2021-02-22 at 14 10 39" src="https://user-images.githubusercontent.com/41292272/108700517-c5503e00-7517-11eb-826a-60224456e84b.png">

The other question is, let's say we will split a platform that has objects from 2 datafiles. But, one of the datafiles didn't have any measurements (It means that there will be no identifier). What should I do in this situation? Should I give the current datetime? One other thing is there might be measurements of datafiles with the same datetime except for milliseconds. That's why I added it as well. But either with it or without it, the maximum characters constraint (10) for the identifier is violated. Should we increase it?

**Comment by IanMayo** [comment]
Hello @BarisSari , I think the solution is easier than you think.

I _think_ this is the process:
1. find platform to be split
2. loop through the sensors for this platform
3. loop through the datafiles for this sensor
4. for each new datafile (after the first):
5. create new platform & sensor, as duplicates of current platform/sensor, with incremental counter on the platform name
6. Swap original datafile sensors for these new ones.


Datafile1 has measurements for 2 sensors (S1, S2) on one platform (P1). 
Datafile2 has measurements for 1 sensors (S1) on one platform (P1). 
Datafile3 also has measurements for 2 sensors (S1, S2) on one platform (P1). 

We process Datafile1, but no changes come from it.
As we process Datafile2, we create P1-1, with sensors S1-1
As we process Datafile3, we create P1-2, with sensors S1-2 and S2-1

We end up with Platforms P1, P1-1 and P1-2

**Note:** the above is _theoretical_ - so it's worth @BarisSari  and probably @robintw double-checking it makes sense.

_Maybe_ it's tidier to "lose" the original P1, and generate all new platforms - so we would end up with P1-1, P1-2 and P1-3.  We're then sure

**Comment by robintw** [comment]
That explanation sounds good @IanMayo, but I think the 'swap original datafile sensors for these new ones' will be a bit trickier, as there isn't a direct mapping between Datafile and Sensor - it all goes via a measurement table like State or Comment. So, we'd need to find all the (for example) State entries that have a source_id of that datafile and a sensor_id of that sensor, and update the sensor to the new sensor that we've created on the new platform. We'd then need to do the same for Comments, Contacts and so on.

Does that make sense @IanMayo, @BarisSari?

In answer to your other question: I think it is sensible to delete the original P1 and just have new P1-1, P1-2 etc, then it's clearer.

**Comment by IanMayo** [comment]
Aah yes, thanks Robin.  Yes - you're right. I've tried to correct the logic above.

**Comment by BarisSari** [comment]
Thanks for the answers, @IanMayo and @robintw. I think I thought it too complex because I didn't want to lose any platform-related object when this operation is done (I delete the original P1 at the end).

I can easily change the code to find measurements of Sensors of the given Platform. So, I think this problem will be solved quickly. However, I have one other question, which was under the image (actually, there were two but the first one will be automatically solved when I update the code for the above):

1. There might be measurements of datafiles with the same datetime except for milliseconds. That's why I added it as well. But either with it or without it, the maximum characters constraint (10) for the identifier is violated. Should we increase it?

**Comment by IanMayo** [comment]
Oops, missed the questions under the image :-)

1. Platform doesn't have any measurements in datafile.  Maybe this is superseded by the new approach, but if there aren't any measurements, then there aren't any sensors to be split/duplicated.

2. Identifier.  Yes. 10 chars is probably too short.  For some platforms we _may_ end up with a manufacturers serial number.   I guess 30 chars is more realistic.
