### ISSUE TITLE
'Show info' action in GUI?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#790]
I had an idea just now...would it be worth having a 'Show info', or 'Show full details' action in the GUI? It would allow you to select a single item in the preview table, and then show all of the fields for that item. It would save the user having to add and remove fields from the display manually until they've seen all the fields they want for that item.

In terms of implementation, it would be very easy: it would just be the left-hand side of the Edit Dialog, displayed by itself in a dialog.

(Yes, as mentioned above, the users could do this already by choosing to edit and then cancelling the dialog, but that's not obvious)

Thoughts @IanMayo?

**Comment by IanMayo** [comment]
Yes, sure.  Maybe "View item" as the command?

I guess the correct place for it is in the `Actions` area.

Hmm, does the focus have to move to the `Actions` area before any of the commands work?  Since we don't use the 1..9 commands in any other area, it would be good if they could be "forwarded" from the Preview area to the Actions area.  Then the user just selects an item and presses `8` (or whatever the number is).

**Comment by robintw** [comment]
Sure, I'll do that.
