### ISSUE TITLE
Loading 5 month old SQLite file

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#792]
I've opened Peyps_Admin, looking at a 5-month old SQLite file (attached)
 that contains lost of data (all data in `tests\sample_data\track_files`).

When I try to view data, it reports `Database tables not found`.  When I try to migrate it, some migrations appear to fail, missing datafile foreign keys.  But, the database does seem usable after the migration is complete - I can browse data and use maintenance tools.

1. What test is being used for `Database tables not found`?
2. What is reason for migration failing?  Is it something we should be concerned about?

[pepys_from_nov.sqlite.zip](https://github.com/debrief/pepys-import/files/6082356/pepys_from_nov.sqlite.zip)

**Comment by BarisSari** [comment]
Hello @IanMayo. 

1. We have [a method](https://github.com/debrief/pepys-import/blob/develop/pepys_import/utils/data_store_utils.py#L180) that checks the number of tables in the database. It returns true if there are 72 or 74 tables in an SQLite database. Since your database is 5-month old, it probably has fewer tables than these numbers. That's why it says `Database tables not found`.
2. I'll check the errors and let you know.

**Comment by IanMayo** [comment]
Ok.  I see it's the wording of the warning the confused me, since it's the same warning as if there are no Pepys tables at all.

Could we change the processing to this please?

**Comment by BarisSari** [comment]
Sure, I'm working on it.
