### ISSUE TITLE
Error while editing values

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#806]
## Version

Rel 5a

## 🐞 Description

An error was thrown while editing a Platform.  Error listing in Screenshot below.

User provided this description:
```
The message on the popup box was not clear to us: Press TAB to move between fields. 
Only non-empty new values will replace current values.
So tried different options:
- leaving all the fields blank except the one we were editing
- deleted the default text in the fields e.g. name = Enter new value (so deleted Enter new value)
but these did not work. What are we not doing right?
```

## 🔢 Steps to Reproduce
[waiting for steps]
- went into maintenance tools
- selected "Platforms"
- selected a platform
- asked to edit platform
- change platform nationality
- try to save, got attached error
- try to delete "Enter text here" prompt text for name, then save. Got another error (this could be because Pepys tried to save an empty string as "name", and failed some constraint)

## 🖥️ Screenshots

![For Ian](https://user-images.githubusercontent.com/1108513/110494574-a642d600-80eb-11eb-81f6-d0fdcbafccc0.PNG)

**Comment by robintw** [comment]
Ok, I think we'll need to improve the wording used for the edit dialog - as they seem to be confused about what they need to do to edit a single field.

You're right that if they delete the 'Enter new value' then they'll get an error because the name isn't allowed to be empty.

I can't see how they got the original error: I've tried following their steps to reproduce on both the current `develop` HEAD and my new PR for Phase 5 part 2, and on both of them editing a platform's nationality works fine. It looks like the screenshot they've sent is from where they've deleted the `Enter new value` text from each field - as it looks like it is complaining that an empty string for the platform_id isn't valid - but I don't quite understand why, as it shouldn't be changing the platform ID anyway...

Could you ask them to try this again, editing the nationality of a platform by just changing the nationality dropdown, and not changing any of the other fields - and then send the error they get.

**Comment by IanMayo** [comment]
> Could you ask them to try this again, editing the nationality of a platform by just changing the
> nationality dropdown, and not changing any of the other fields - and then send the error they get.

Sure, they're back on this on Thursday, though we may be pushing a new release tomorrow.

**Comment by IanMayo** [comment]
This error didn't occur today, after the users got the hang of the edit panel.
