### ISSUE TITLE
Package of sample coverage data

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#845]
I've produced some mock data, to drive the Coverage view.

The source was 24 hour of E-Trac data from an unclass data file. The mmsi, date, location and platform names were modified.

The data was then sliced into 4 different datafiles.   Platform tracks are spread across one or two files, with segments from a few minutes to several hours.  Each datafile was then loaded into a new SQLite database.

The defaults resolver was used, with the `Nationality` set to `Chad`.  This should allow all of this data to be easily removed.

We can _simulate_ the loading of data during a day by loading these slices one at a time.  They can be loaded into the PostGres database by using the `Merge Snapshot` functionality of `Pepys-Admin`.   When I tried to test-drive this the merge failed (error log also attached - it may have been a migration issue, or it may have been because we haven't run `merge` from the command line for some time).

The 4 sqlite files are  in the attached zip-file.

[SlicedData.zip](https://github.com/debrief/pepys-import/files/6303694/SlicedData.zip)

[MergeError](https://user-images.githubusercontent.com/1108513/114552465-89567100-9c5c-11eb-8588-eeb28d327bac.png)

**Comment by robintw** [comment]
The merge error looks like some sort of migration issue: it seems to be saying that the PlatformTypes table doesn't exist. Are you running this on a local database or on TracStor? That table definitely exists on TracStor.

I can have a play with this later (on childcare at the moment) - are you happy for me to import the first snapshot into TracStor as a test?

**Comment by IanMayo** [comment]
Hello Robin - yes, I'm sure you're correct.

I was using a deployment dated 27th March, I think.  Yes, you're welcome to import one or more of them to TracStor.  Aah, maybe just the first, then verify it's possible to delete all the loaded data by deleting all platforms from `Chad`.

Maybe each SQLIte file just needs to be opened in an up-to-date `Pepys-Admin`, and run `migrate` over it.

**Comment by robintw** [comment]
I'm investigating this now. There seemed to be a weird permissions error on the TracStor database, which I've sorted, but there also seem to be some problems with the merge code which I'm now trying to fix.

Which would you like me to prioritise? Fixing this or getting the Tasks GUI finished?

**Comment by IanMayo** [comment]
Afternoon @robintw - the Tasks GUI remains the higher priority.  If the data merge was quick & easy then it would have been convenient to slip it in, but if it's non-trivial then the Tasks GUI is the one to push.

I've produced some _pretty crude_ mock coverage data to let Ivan get started: https://github.com/debrief/pepys-timeline/issues/2#issuecomment-818842706

**Comment by robintw** [comment]
This has now been fixed in the #833 PR (it was too complex to try and separate it out into a separate PR, as lots of changes modified the same files - hope that's ok).

The error was quite complex, but the fix was quite simple. To fix it, we need to run some SQL whenever we open a Postgres database which sets the search_path (where it looks for tables if a schema isn't specified). This is important for merging, as the objects that are copied from SQLite to Postgres don't have a schema, so they need a proper search path to be able to find one. It seems that we also need to initialise the PostGIS extension in this SQL code - I'm not really sure why, but it only works if you do so. I've commented this to make it clear what's going on.

I'm deliberately copying my notes on reproducing this bug here, in case we run into similar problems in the future - then we can save ourselves some time investigating. Basically, I found that it mattered whether you closed Pepys Admin between doing different operations. If you initialised the schema and then ran a merge, it worked fine, but if you initialised the schema, then _closed Pepys Admin_, and then ran a merge, it failed. This was because initialising the schema set the search_path, but this wasn't set when the Postgres database was opened.

## Notes:
Steps to reproduce:
    1. Create a database
    2. Open Pepys Admin
    3. Initialise database schema and import reference and metadata
    4. Exit Pepys Admin
    5. Open Pepys Admin and run merge databases
    6. Fails with error "relation Platforms does not exist"


If we don't exit then it works fine.

If we run Pepys Admin, run Status, and then run merge, it works (think this is incorrect? Does it work sometimes? all the time? sometimes fails on Datafiles?)

If we run Pepys Admin, run Create schema, then run merge, it works.

This all still fails if you do the following sequence:
    1. Export a snapshot from Pepys Admin
    2. Import some new data to the snapshot SQLite db (eg. a REP file with Pepys Import)
    3. Merge that snapshot back into the database
(basically, it has to have something new that it tries to copy across)

We've now replicated this error in the tests - running:
    pytest tests/test_merging.py::TestExportAlterAndMerge_Postgres -s
will fail

Interestingly, it fails on PlatformTypes in the test, whereas when we do the steps above in Pepys Admin, it fails on Platforms (or occasionally on Datafiles - but we can't work out how we got it to fail on Datafiles - maybe it was when we'd tried to run Status but not Create schema)

These errors all seem to still occur from when the merging code was first introduced: checking out the old revision (1b44e2687db1bb2d013079f502568b8902ab9982) and running an export, followed by a merge, but with closing Pepys Admin in the middle, still gives the error

Workaround: Make sure you have run the migrations, so your database is up-to-date. Then just run the create schema option before doing your merge.

Fix: Set the search path (and load the PostGIS extension) when loading any Postgres database.

**Comment by IanMayo** [comment]
Nice work, thanks @robintw

**Comment by IanMayo** [comment]
Requirement for this has mostly passed now.  Will re-open if this sample data is required.
