### ISSUE TITLE
Display message of the day

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#884]
The users are looking forward to the timeline displaying a message of the day.

There were thoughts that this could show issues to focus on, but the client lead was keen to see `Manager of the day: Daisy`.

We still need to work on layout/design for the timeline page, but a large central text box occupying 50% of width would be a start.

The table will be implemented in this issue: https://github.com/debrief/pepys-import/issues/871

It is expected that a call to the options be made just after the existing update cycle.

**Comment by IanMayo** [comment]
I've just had a play with the deployed version.  There is a value in `ConfigOptions` for MotD, but we're not loading it.

Re-opening:
![image](https://user-images.githubusercontent.com/1108513/117652534-31435980-b18b-11eb-9848-3f28a97b2147.png)

**Comment by IanMayo** [comment]
Aah, I see. Do we handle this is Alembic @robintw ? I expect @arunlal-v can fix it, but that fix won't be present on client network.

**Comment by robintw** [comment]
Ah, that must have been because we have to run the migration script as the admin user on TracStor, and it seems like that doesn't create access privileges for the other users.

We have created the `Serials`/`Wargames` etc tables using Alembic in the same way that we have for the `ConfigOptions` table, and the users have had access to those fine - so I think this is an artefact of the way that our TracStor instance is configured, and that the users won't have a problem with it. Therefore, setting the TracStore `ConfigOptions` table to have permissions to be read/updated by the `tracstor_view` user should be all we need to do - and everything for the user should work fine.

Having said that, it would be good if @krsnik93 could add some nice error handling so that if we can't access the table (or any of the tables) for whatever reason, we get a nice explanatory error message, ideally passing through the error message from the underlying library (which should give us a 'Permission error' or similar string).

**Comment by krsnik93** [comment]
:+1: 

That can be a part of this issue: https://github.com/debrief/pepys-import/issues/897

**Comment by IanMayo** [comment]
Sure - yes, good summary @robintw
