### ISSUE TITLE
Potential migration issue

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#923]
The Debrief dialog used to import Pepys data was failing, so I opened Pepys-Admin to check if the PostGres database was running.

Pepys-Admin opened, and displayed the valid connection details.  When I tried to use `View data` to examine the data, it reported `Database tables not found. Do you need to initialise?` (or something like that).

A few minutes later I opened Pepys-Admin again, again it displayed the valid connection details. But, this time when I tried to view data, it said `Please run database migration to bring tables up to date`.  When I tried to run the migration, it reported:  `Exception details: Requested revision 00116b58f22e overlaps with other requested revisions ff4215cb3d30`.

I used PGAdmin to opened the `alembic_versions` table, and it contained the above two rows.

Note: the migration script log also included `len(table_names)=42`.

I see the two above migration ids in the `migrations` folder, though they are from 3 and 7 months ago.

**Comment by robintw** [comment]
Does this need dealing with now @IanMayo, or can it wait until we get the contract sorted? I'm still recovering from Covid, but I might be able to do a bit on it soon if needed.

**Comment by IanMayo** [comment]
Have replied in Slack.

**Comment by robintw** [comment]
For reference, the two migrations listed above are:

`00116b58f22e` from 1st Dec 2020, which adds the HelpTexts table
`ff4215cb3d30` from 26th April 2021, which adds a unique constraint for the Serials table

These are both listed as the current version in the `alembic_version` table, and therefore the migration procedure doesn't know what to do.

The only migrations which come _after_ `ff42...` are:
- Adding the `ConfigOptions` table
- Adding stored procedures for dashboard
- Adding stored procedures for Debrief (potentially a reason why the Debrief import isn't working @IanMayo?)
- Fixing pagination in the Debrief procedures

My suspicion at this stage is that `ff42...` is the _correct_ version that should be in the `alembic_version` table, and the `0011...` version was added by an out-of-date Pepys version that someone ran. Therefore, the way to fix this is to remove the row containing `0011...` and then run the migration again.

However, before doing that I want to check that the database is actually at the `ff42` version. To do this we can check that:
- A constraint called `uq_Serial_serial_number_wargame_id` exists on the `Serials` table.
- The `ConfigOptions` does _not_ exist

So, @IanMayo - do you think we can get them to check that using pgAdmin?

Assuming they come back to us and confirm those two things, then we just need to do run a DELETE statement to delete from the `alembic_versions` table, and then run the migrations from within Pepys Admin to get them fully up to date.

**Comment by IanMayo** [comment]
Today I renamed the `datafiles_for` stored procedure in `acugis` postgres instance to `datafiles_for2`, and in Debrief when I clicked `Apply` I got the same error message that users are seeing. This reinforces @robintw 's theory above. Now building new Debrief release that gives more discrete (and helpful) error message.

**Comment by IanMayo** [comment]
These steps sent in:
```
## Check One
1. Open SLAN
2. Open PGAdmin
3. Open Pepys database (should be in saved servers on left-hand side)
4. Expand `Schemas`
5. Expand `Tables`
6. Expand `Serials`
7. Expand `Constraints`
8. Check for presence of constraint called: `uq_Serial_serial_number_wargame_id `

## Check two
(assume PGAdmin already open)
1. Look in `Tables` listing
2. Check for presence of `ConfigOptions` table.

That will give us two answers, please:
a. if the 'uq_Serial_serial_number_wargame_id' constraint is present in "Serials"
b. if the `ConfigOptions` table is present
```

**Comment by IanMayo** [comment]
Just did site visit, to run through diagnostics & fix.

I logged in, ran PGAdmin4 & connected to the database.

* The `config options` table was missing
* The `uq_Serial_serial_number_wargame_id ` constraint was present in `Serials`

This confirmed Robin's suspicion.  

I then ran `delete from alembic_verison where version_num = 00116b58f22e` (or something very close to that).

I re-opened the table, and confirmed the presence of just one row in `alembic_versions`

I opened pepys-admin: S/W Version: 0.0.25 //  Build date: 2021-04-28 12:56:15.  Connected to PostGres

I ran migrate, and confirmed I was happy to change the database structure.

```
Alembic migration command running see output below
len(table_names)=42
Database tables are going to be created by Alembic
INFO [Alembic.runtime.migration] Content impl PostgresqlImpl
INFO [Alembic.runtime.migration] Will assume transactional DDL
```

Then it displayed the default `pepys-admin` menu.

I went into `view data` to check things were working, but on most commands `pepys-admin` reported:
```
len(table_names) = 42
Please run database migration to bring tables up to date.
```
and then re-displayed the menu.

**Comment by robintw** [comment]
Thanks @IanMayo - this is really interesting.

So, the reason the migration didn't seem to do anything was because there was nothing to do: the database is at the latest version given the Pepys version that is in use. We can tell this by looking at the build date given in the Pepys output (`2021-04-28`) and comparing this to the list of migrations in the `migrations/postgres_migrations` folder. This shows that the most recent migration as of that date was `2021-04-26_ff4215cb3d30_add_unique_constraint_for_serials.py` - which is the migration that the database thought it was at.

So, the question is: why does alembic think the database is at the most recent version, but Pepys doesn't think the database is up-to-date.

Looking at our [list of releases](https://github.com/debrief/pepys-import/releases), there are multiple pre-release versions that have been released since 0.0.25 (the one they're using), but no full releases since then. However, they must have been using some of the pre-release versions 'in anger' because I remember them using the new maintenance tools to clean up their database. I suspect this could be another problem caused by multiple different versions of Pepys - at any rate, having multiple versions in use won't be helping.

I also did some fixes to Pepys a while back that fixed a number of bugs to do with Pepys showing the `Please run database migration to bring tables up to date.` message when it shouldn't. I'll do a git blame to look up when those changes occurred, and see whether they would have been in 0.0.25 or not.

I suspect the easiest way to fix this would be to update to the latest version (or potentially do a 'proper' release rather than a pre-release). I imagine this would get everything in step and fix the problem.

**Comment by IanMayo** [comment]
> or potentially do a 'proper' release rather than a pre-release

Yes, good plan.  We just have to decide if we defer creating the release until after the new _preventative measure(s)_ have gone in.

**Comment by IanMayo** [comment]
> I suspect the easiest way to fix this would be to update to the latest version (or potentially do a 'proper' release rather than a pre-release). I imagine this would get everything in step and fix the problem.

Sure, will create/package new release, and call in to be around for upgrade/migration.

**Comment by IanMayo** [comment]
I'm going to conduct the next release/update myself.  I want to maximise the chances of the fix working, and get maximum value out of doing the release myself.

Here are the tests/inspections I think could be of value:
* Before update:
    * count of tables & stored functions
    * double-check alembic version
    * verify that `pepys-admin` still failing to connect to database
* Conduct update & migration
* After update:
    * check new version (0.0.26) and build date (today)
    * count of tables & stored functions
    * double-check alembic version
    * check `pepys-import` opens
    * check `pepys-import` can `View data`
    * check `pepys-timeline` runs

**Comment by IanMayo** [comment]
Just did migration on trac-stor, ran these two migrations:
![image](https://user-images.githubusercontent.com/1108513/129551251-74ab354e-296c-419b-a86e-f4ff99c8bd96.png)

**Comment by IanMayo** [comment]
Ok, I modified the number of tables expected, and am now playing with `View data`.

When I select to view `Tasks` I get this red error:
```
Attribute error! Please check the error message: module `pepys_import.core.store.postgres_db` has no attribute `Task`
```

When I ask to view `Serials` there is this red error:
```
Attribute error! Please check this error message: `Serial` object has no attribute `participants_platform_name`
```

When I ask to view `Wargame Participants` it worked.

I checked from PGAdmin, and each of the above had at least one row present.

Pepys maintenance worked ok for `Platforms` and  `Wargame Participants`.

**Comment by IanMayo** [comment]
Ok.  @robintw & I have chatted.

Maybe `41` _is_ the correct number of tables.  I've compared client database to tracstor.  Client database also has `Participants` and `Tasks`.  These were dropped when we moved away from recursive tasks.

Either they weren't dropped in a migration (due to permissions), or they were dropped in one migration and reinstated in another migration (that was actually from an older Pepys).

I'll delete these unwanted tables from the client database.

Account used to access database certainly has full permissions for database access (`pos*res`).

**Comment by robintw** [comment]
I'm 99% sure that the following is what happened:

- Everything is working at the clients (the previous situation they were in before they told us about this problem)
- Someone ran the old version of Pepys that is hanging around somewhere on their network. This decided that the database didn't match what it expected, so it either automatically created the tables it thought was needed (certain older versions could do this automatically, which was a bad idea and this 'feature' has been removed) or it asked them to run a migration and they did so
- This led to the old version of Pepys creating the `Tasks` and `Participants` tables - as that old version of Pepys expected to see those tables. In fact, those tables had been deliberately removed by one of the migrations released _after_ that old version of Pepys was released
- The new version of Pepys counted the tables when it connected to the database, and found 43 rather than the 41 that it was expecting - and threw an error. The mismatch is because those Tasks and Participants tables had been incorrectly recreated.

Yet again, it's all because of this old version of Pepys causing problems!

I have just had an idea about how we could potentially disable this old version - see #939.

In the meantime, I think we should alter Pepys to accept either 43 or 41 tables, as if the old version of Pepys is run again then those tables will be recreated. Having two empty Tasks/Participants tables sitting around doesn't actually do any harm (though it is a bit untidy), so it wouldn't be a massive problem to have them there - and it would save them getting into this state again.

As for the other two problems you experienced:

1. The `Tasks` table was in the list of tables to view in View Data because it exists in the database, but it failed to view it because there was no matching Python class - because the table shouldn't have been in the database.

2. The error viewing the `Serials` table was because it was expecting the association proxy called `participant_platform_name` to be called `participants_platform_name` (note the plural). I'll create a separate issue to fix this, add better error handling, and improve testing of this area of the code.

**Comment by IanMayo** [comment]
Closing. Fixed via manual intervention. Pepys now tries to prevent above happening.
