### ISSUE TITLE
Prevention of older versions of Pepys interacting with newer version of the database.

### ISSUE THREAD

**Issue by SamWilliams-dev** [debrief/pepys-import#939]
## 🐞 Overview

We have experienced issues where old versions of Pepys connect to a newer version of the database, and this causes various problems (including the old version of Pepys messing up the internal version of the database). Therefore, we should add code to Pepys that stops it connecting to the database if the database version (as stored in the alembic_versiontable) is a version that is newer than any that that version of Pepys knows about (ie. the current database version is not a 'known version' for this version of Pepys).

**Comment by IanMayo** [comment]
@robintw - it would be useful to learn more about the issue here.  Am I right in thinking that the only was an old version of Pepys could mangle the database is via an attempted migration?  Aah, or are there occasions when Pepys thinks it needs to initialise the database when it first starts (as if it's a vanilla database instance).
