### ISSUE TITLE
PowerShell scripts to create Pepys shortcuts

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#96]
For the MS-Windows "Send to" integration we require Windows Shortcut files to the pepys batch file.

These have to be created after deployment, since they contain the absolute path to the batch files.

When creating them, we should assign the Pepys icon (as found in the `bin` folder.

A second shell script should copy the shortcuts to the `AppData\Roaming\Microsoft\Windows\SendTo\` folder for the current user.

Note: the first script will only be run once, as user with privilege to write to deployed folder,  whereas the second script would be used by any Pepys user.

**Comment by robintw** [comment]
I've implemented this in #89, but while documenting it just now I realised that we might not need to have two scripts. At the moment we're creating the shortcuts once and then running a separate script _once for each user_ to copy them to the SendTo folder. We could replace this with a single script, again run _once per user_, that creates the shortcuts directly in the SendTo folder.

The benefit of this is that it removes a potential issue that I am currently documenting: in the current system, `create_shortcuts.bat` must be run from a user who accesses the network drive through the same drive letter as the users - otherwise the shortcut will point to the wrong place. This may not be the case - for example, an administrator may have different network drive mappings set up - and therefore this would fail.

What do you think about switching to have a single script instead?

**Comment by IanMayo** [comment]
Nice thinking @robintw . Single script!
